In [1]:
using InstantiateFromURL

# activate the QuantEcon environment
activate_github("QuantEcon/QuantEconLecturePackages", tag = "v0.9.5");

┌ Warning: On Windows, creating file symlinks requires Administrator privileges
└ @ Base.Filesystem file.jl:789


In [2]:
using LinearAlgebra, Statistics, Compat

In [6]:
try
    array = [1.0, "a"]
catch e
    print(e)
end

2-element Array{Any,1}:
 1.0 
  "a"

In [9]:
[1 2 3 4 5; 6 7 8 9 10]

2×5 Array{Int64,2}:
 1  2  3  4   5
 6  7  8  9  10

In [14]:
array_undef = Array{Float64}(undef, 2, 2)

2×2 Array{Float64,2}:
 1.0735e-313   3.92129e-316
 3.92473e-316  3.92291e-316

In [19]:
a = Set([1, 2, 3])
b = copy(a)
push!(b, 4)
print(a)

Set([2, 3, 1])

In [23]:
a = rand(2, 2)

2×2 Array{Float64,2}:
 0.00466978  0.366396
 0.660712    0.645361

In [24]:
a = [1 2; 3 4]
b = a' # transpose
c = Matrix(b)  # convert to matrix
d = collect(b) # also `collect` works on any iterable
c == d

true

In [25]:
d

2×2 Array{Int64,2}:
 1  3
 2  4

In [35]:
val = [1, 2]
y = [0, 0]

function f!(out, x)
    out .= [1 2; 3 4] * x   # MISTAKE! Should be .= or [:]
    print(out)
end
f!(y, val)
y

[5, 11]

2-element Array{Int64,1}:
  5
 11

In [36]:
a = [1, 2]
b = [1, 2]
a == b

true

In [37]:
a === b

false

In [38]:
a = b
a === b

true

In [39]:
a ⋅ b

5

In [40]:
a = [1, 2, 3, 4]

4-element Array{Int64,1}:
 1
 2
 3
 4

In [41]:
b = reshape(a, 2, 2)

2×2 Array{Int64,2}:
 1  3
 2  4

In [46]:
b = copy(b)

2×2 Array{Int64,2}:
 1  3
 2  4

In [48]:
b[4] = 5

5

In [49]:
a

4-element Array{Int64,1}:
 1
 2
 3
 4

In [50]:
b

2×2 Array{Int64,2}:
 1  3
 2  5

In [52]:
c = [1 2; 3 4]

2×2 Array{Int64,2}:
 1  2
 3  4

In [53]:
c[1][1]

1

In [54]:
c[4]

4

In [65]:
A = zeros(Int, 4, 4, 4)

4×4×4 Array{Int64,3}:
[:, :, 1] =
 0  0  0  0
 0  0  0  0
 0  0  0  0
 0  0  0  0

[:, :, 2] =
 0  0  0  0
 0  0  0  0
 0  0  0  0
 0  0  0  0

[:, :, 3] =
 0  0  0  0
 0  0  0  0
 0  0  0  0
 0  0  0  0

[:, :, 4] =
 0  0  0  0
 0  0  0  0
 0  0  0  0
 0  0  0  0

In [67]:
b[2, 2]

5

In [69]:
a = 10:12        # a range, equivalent to 10:1:12
@show Vector(a)  # can convert, but shouldn't

b = Diagonal([1.0, 2.0, 3.0])
b * a - [1.0; 2.0; 3.0]

Vector(a) = [10, 11, 12]


3-element Array{Float64,1}:
  9.0
 20.0
 33.0

In [78]:
maxval = 10
minval = 0.0
numpoints = 10
a = range(0, 10, length=10000)
# or range(minval, stop=maxval, length=numpoints)
@show Vector(a);

Vector(a) = [0.0, 0.0010001, 0.0020002, 0.0030003, 0.0040004, 0.0050005, 0.0060006, 0.0070007, 0.0080008, 0.0090009, 0.010001, 0.0110011, 0.0120012, 0.0130013, 0.0140014, 0.0150015, 0.0160016, 0.0170017, 0.0180018, 0.0190019, 0.020002, 0.0210021, 0.0220022, 0.0230023, 0.0240024, 0.0250025, 0.0260026, 0.0270027, 0.0280028, 0.0290029, 0.030003, 0.0310031, 0.0320032, 0.0330033, 0.0340034, 0.0350035, 0.0360036, 0.0370037, 0.0380038, 0.0390039, 0.040004, 0.0410041, 0.0420042, 0.0430043, 0.0440044, 0.0450045, 0.0460046, 0.0470047, 0.0480048, 0.0490049, 0.050005, 0.0510051, 0.0520052, 0.0530053, 0.0540054, 0.0550055, 0.0560056, 0.0570057, 0.0580058, 0.0590059, 0.060006, 0.0610061, 0.0620062, 0.0630063, 0.0640064, 0.0650065, 0.0660066, 0.0670067, 0.0680068, 0.0690069, 0.070007, 0.0710071, 0.0720072, 0.0730073, 0.0740074, 0.0750075, 0.0760076, 0.0770077, 0.0780078, 0.0790079, 0.080008, 0.0810081, 0.0820082, 0.0830083, 0.0840084, 0.0850085, 0.0860086, 0.0870087, 0.0880088, 0.0890089, 0.090009, 0

In [82]:
a = [1 2 3]

1×3 Array{Int64,2}:
 1  2  3

In [85]:
function f(parameters)
    α, β = parameters  # good style, less sensitive to errors
    return α + β
end

parameters = (α = 0.1, β = 0.2)
f(parameters)

0.30000000000000004

In [87]:
array = [1, "a"]

2-element Array{Any,1}:
 1   
  "a"