In [17]:
~false

true

In [26]:
teste = "Hey, okay $(72-71)"

"Hey, okay 1"

In [25]:
teste[:]

"Hey, okay"

In [31]:
println("Hey $(2 + 2)")

Hey 4


In [32]:
@p 3

LoadError: UndefVarError: @p not defined

In [35]:
try
    some_other_var # => ERROR: some_other_var não definida 
catch e
    println(e)
end

1

In [34]:
some_other_var = 1

1

In [36]:
array = [1, 2, 3, 10]

4-element Array{Int64,1}:
  1
  2
  3
 10

In [40]:
array[end]

10

In [42]:
matrix = [1 2; 3 4]

2×2 Array{Int64,2}:
 1  2
 3  4

In [43]:
matrix * 2

2×2 Array{Int64,2}:
 2  4
 6  8

In [44]:
matrix

2×2 Array{Int64,2}:
 1  2
 3  4

In [50]:
append!(array, [1, 2, 3])

9-element Array{Int64,1}:
  1
  2
  3
 10
 11
 11
  1
  2
  3

In [53]:
pop!(array)

1

In [58]:
pop!(array)

11

In [59]:
array

5-element Array{Int64,1}:
  1
  2
  3
 10
 11

In [61]:
shift!(array)

UndefVarError: UndefVarError: shift! not defined

In [63]:
push!(array, 1)

6-element Array{Int64,1}:
  1
  2
  3
 10
 11
  1

In [65]:
sort(array)

6-element Array{Int64,1}:
  1
  1
  2
  3
 10
 11

In [66]:
array

6-element Array{Int64,1}:
  1
  2
  3
 10
 11
  1

In [67]:
sort!(array)

6-element Array{Int64,1}:
  1
  1
  2
  3
 10
 11

In [73]:
a = array

6-element Array{Int64,1}:
  1
  1
  2
  3
 10
 11

In [88]:
try
araray[0] # => ERROR: BoundsError() in getindex at array.jl:270
    #a[end+1] # => ERROR: BoundsError() in getindex at array.jl:270
catch e
println(e)
print(e)
println(e)
print(e)
end

UndefVarError(:araray)
UndefVarError(:araray)UndefVarError(:araray)
UndefVarError(:araray)

In [92]:
a = [1:5;]
splice!(a, 2:3)

2-element Array{Int64,1}:
 2
 3

In [93]:
a

3-element Array{Int64,1}:
 1
 4
 5

In [94]:
1 in a

true

In [95]:
2 in a

false

In [96]:
length(a)

3

In [101]:
t = (1, 4, 10)
try
    #t[1] = 0
catch i
    println(i)
end

In [104]:
(1,) == 1 == 1

false

In [105]:
dict = ["um"=>"one", "dois"=>"two"]

2-element Array{Pair{String,String},1}:
   "um" => "one"
 "dois" => "two"

In [109]:
print(dict[1])

"um" => "one"

In [111]:
dict["one"]

ArgumentError: ArgumentError: invalid index: one of type String

In [112]:
filled_dict = ["one"=> 1, "two"=> 2, "three"=> 3]
# => Dict{ASCIIString,Int64}

# Veja os valores com []
filled_dict["one"]

ArgumentError: ArgumentError: invalid index: one of type String

In [116]:
values(filled_dict)

3-element Array{Pair{String,Int64},1}:
   "one" => 1
   "two" => 2
 "three" => 3

In [117]:
filled_dict

3-element Array{Pair{String,Int64},1}:
   "one" => 1
   "two" => 2
 "three" => 3

In [120]:
in(("one", 1), filled_dict) # => true

false

In [124]:
[1 2; 3 4]

2×2 Array{Int64,2}:
 1  2
 3  4

In [132]:
lista = [1, 2, 3, 4, 5]
for numero in lista
    print("$(numero) - ")
end

1 - 2 - 3 - 4 - 5 - 

In [140]:
array = [7, 2, 5, 7, 1]

5-element Array{Int64,1}:
 7
 2
 5
 7
 1

In [141]:
for i in eachindex(array)
    println(array[i], i)
end

71
22
53
74
15


In [142]:
print(zeros(5))

[0.0, 0.0, 0.0, 0.0, 0.0]

In [144]:
ϵ_sum = 0.0 # careful to use 0.0 here, instead of 0
m = 5
for ϵ_val in ϵ[1:m]
    ϵ_sum = ϵ_sum + ϵ_val
end
ϵ_mean = ϵ_sum / m

-0.10003009510777308

-0.10003009510777308

In [153]:
ϵ_mean ≈ sum(ϵ[1:m]) / m

true

In [154]:
A = 0
B = 0.0
print(typeof(A), typeof(B))

Int64Float64